### PR TITLE
Clarify GitHub Blame command in README.md

### PR DESCRIPTION
**Pull request by cletusw**
I had no idea until I looked at the code that you could select some text and then the GitHub Blame command would highlight that line in the blame. Maybe that could be noted in the README?

### CODE REVIEW

**Comment by cletusw** [comment]
Actually, it may make sense to extend this so that it brings you to whatever line you have the cursor at, even if nothing's selected. Just a thought.

**Comment by bgreenlee** [comment]
Thank you. That's actually true for the Remote URL commands as well. I'll merge this and then update those.

**Comment by bgreenlee** [comment]
I don't want to always highlighting the line the cursor is on because more often than not I just want to share the file's URL and not highlight a line.

**Comment by cletusw** [comment]
Sounds good. Thanks for a great plugin!

**Pull request merged**
