### PR TITLE
Support other default branches

### LINKED ISSUE #123: Support other default branches
We use `next-master` for our primary development branch; some places use `develop` or `main` or `default`. It'd be great if the `Open Remote URL in Browser (master)` and related commands could be configured to use a different branch.

### PR DESCRIPTION
**Pull request by MaxPhilips**
Fixes #123

I've set the new default- default branch to main with this PR, it may be desired to not modify that behavior of the plugin, we could change which default is bundled with the install if that is preferred

I think the best was to fix this would be to create dynamic Command Palette entries with the exact branch name present as applicable, but I don't know if that is possible, so I've switched the descriptions from "View (master)" to "View (default branch)"

### CODE REVIEW

**Comment by MaxPhilips** [comment]
I tested this manually by loading the plugin directly

As far as I can tell, all functionality should be maintained, and if you now have a default branch configured that isn't present in the repository you are interacting with, you get the normal `fatal: no such branch: 'main'` error dialog

**Comment by bgreenlee** [comment]
Looks good. Thank you!

**Comment by MaxPhilips** [comment]
@bgreenlee - does this plugin have a release schedule any longer? based on your other recent comment it seems maybe not :)

I'm interested in consuming this change beyond just sideloading the plugin. Could you let me know if there's anything I can assist with to prepare another release for package control? I'd be willing to help out as a repository maintainer if you are focusing on other things

**Comment by bgreenlee** [comment]
Hmm, I thought just pushing to master was enough to update package control. It's been a while since I've done this, though.

I'm happy to add you if you'd like to help maintain this!

**Comment by bgreenlee** [comment]
I updated the version to 1.4.0 and tagged it...and added you as a collaborator.

**Comment by MaxPhilips** [comment]
thanks for the add!

hm... I don't know how package control works. I see that the new README from this PR has made it to the Readme section here: https://packagecontrol.io/packages/sublime-github, but also the plugin version is still 1.3.1, and when I attempt to upgrade the package in my ST3 I don't have any upgrades available

in the package_control_channel, I see this plugin is added with tags: true https://github.com/wbond/package_control_channel/blob/master/repository/s.json#L4327 so based on packagecontrol docs I think we are just waiting for the new tag you created to be parsed ?

**Comment by bgreenlee** [comment]
Yep, they've picked it up, so should be good now. Sorry for that!

**Pull request merged**
