### PR TITLE
Add commands to generate GitHub permalink URLs

### PR DESCRIPTION
**Pull request by wearhere**
i.e. URLs that reference the current HEAD of the current branch, like if you
visited a remote URL and pressed ‘y’, as described here
https://help.github.com/en/articles/getting-permanent-links-to-files.

This commit adds permalink equivalents for all commands except “Edit”,
since GitHub only supports editing files on branches.

Tested that every URL command works as expected.

### CODE REVIEW

**Comment by wearhere** [comment]
Wow what a fast response, thank you! Also thanks for a great plugin in general, invaluable to be able to copy GitHub URLs from the editor as way of pointing fellow devs to some bit of code.

**Comment by wearhere** [comment]
@bgreenlee what's the process for this change being picked up in the Package Control version of the plugin?

**Comment by bgreenlee** [comment]
It should be automatic. I'm not sure how often they scan.

**Comment by bgreenlee** [comment]
Ah, I probably needed to bump the version. Just did that.

**Pull request merged**
